// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CopyTextController from "./copy_text_controller.js"
application.register("copy-text", CopyTextController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import ToggleHiddenProximateController from "./toggle_hidden_proximate_controller.js"
application.register("toggle-hidden-proximate", ToggleHiddenProximateController)

import UtilController from "./util_controller.js"
application.register("util", UtilController)
