version: "3.6"
services:
  db:
    image: docker.io/postgres:12
    volumes:
      - database:/var/lib/postgresql/data
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PW}

  app:
    image: ghcr.io/jthornhill/wgolf:main
    user: "${APP_UID}:0"
    build: "./"
    volumes:
      - tmp:/app/log
      - tmp:/app/tmp
      - tmp:/app/tmp/pids
    ports:
      - "127.0.0.1:${RAILS_PORT}:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:${DB_PW}@db:5432"
      HOME: /home/docker-user
      PORT: "${PUMA_PORT}"
      RAILS_ENV: "${RAILS_ENV}"
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
      RAILS_SERVE_STATIC_FILES: "${RAILS_SERVE_STATIC_FILES}"
      TZ: "UTC"
    depends_on:
      - db
    working_dir: /app
    hostname: ${APP_NAME}
    tty: true
    command: /app/bin/app-start

volumes:
  database:
  bundle:
  node_modules:
  home:
  tmp:
    driver_opts:
      type: tmpfs
      device: tmpvol

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1274
