services:
  app:
    volumes:
      - .:/app
      - ~/.dc-devel/${APP_NAME}/screenshots:/app/tmp/screenshots
      - ~/.dc-devel/.guard/${APP_NAME}:/guard
      - bundle:/app/vendor/bundle
      - node_modules:/app/node_modules
      - home:/home/docker-user
    ports:
      - "127.0.0.1:${RAILS_PORT}:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:${DB_PW}@db:5432"
      HOME: /home/docker-user
      PORT: "${PUMA_PORT}"
      RAILS_ENV: "${RAILS_ENV}"
      TZ: "UTC"
    depends_on:
      - db
    working_dir: /app
    hostname: ${APP_NAME}
    tty: true
    command: /app/bin/dev
